### ISSUE TITLE
How to know if files flagged or identified as abusive

### ISSUE THREAD

**Issue by ewwink** [googledrive/PyDrive#106]
How to know if files flagged or identified as abusive?

**Comment by RNabel** [comment]
Following a quick search through the Google Drive API, this doesn't seem to be (easily) possible. The API does not seem to expose this information explicitly. 

According to the docs, there is a `labels` array which may contain this information. You can access the labels with `FetchMetadata(all_fields=True)` like so:

```python
file1 = drive.CreateFile({'id': '<some file ID here>'})

file1.FetchMetadata(fetch_all=True)  # fetch_all=True downloads all metadata fields.
# Alternatively, you download the 'labels' field only.
file1.FetchMetadata(fields='labels')
print(file1['labels'])
```

All the field names are documented in the official Google Drive API documentation:
https://developers.google.com/drive/v2/reference/files

PyDrive metadata functions are documented here:
https://pythonhosted.org/PyDrive/filemanagement.html#download-file-metadata-from-file-id

**Comment by ewwink** [comment]
thanks for your references, but it not available in `labels`, its available in `copyable` and `capabilities/canCopy `. too bad API v3 return different result for `capabilities.canCopy` it return true while v2 return false

**Comment by RNabel** [comment]
Ah, I'm sorry to hear that. In this case, you will have to use the google api client library; link: https://github.com/google/google-api-python-client

Good luck!
