### ISSUE TITLE
Only access to files created by my app

### ISSUE THREAD

**Issue by cvpe** [googledrive/PyDrive#108]
I use pydrive on IOS/Pythonista and I'm able to create/upload files on my Google Drive.
But drive.ListFile only gets only these just created files or folders, not all other existing ones.
Perhaps is it linked to the scope parameter /drive.file instead of /drive but is it possible to change this attribute?

**Comment by ehdeeh** [comment]
For the default config it should, according to their documentation use /drive. You can force it to use whichever scopes you'd like if you create your own settings.yaml file per: https://pythonhosted.org/PyDrive/oauth.html?#automatic-and-custom-authentication-with-settings-yaml

I should note that the default settings.yaml file is indeed limited to drive.file.  I ran into the same issue and had to swap those out and re-authenticate to access files outside of the app's scope.

**Comment by cvpe** [comment]
Thanks for your answer

**Comment by cvpe** [comment]
It seems logic that scope would be defined at user creation, thus on Google server and not at client side, no?

**Comment by ehdeeh** [comment]
I can't speak with any authority on this one, only what's worked for me but I would think that the oauth permission set is defined at time of authentication by the original oauth request made.  So, if you save your token you'd have to re-authenticate as I did when I deleted my credentials.json file and logged in again.  Here's what I have in for my `oauth_scope` in my `settings.yaml` in case it helps, though I'm unsure if I even need `drive.metadata`:

```
oauth_scope:                                                                                                                                                                        
  - https://www.googleapis.com/auth/drive
  - https://www.googleapis.com/auth/drive.metadata
```

**Comment by cvpe** [comment]
Thanks a lot for your advice, I'll try in some days.

**Comment by cvpe** [comment]
I'm not able to do it, even by creating a new credential...
I suppose I'm doing something bad

**Comment by cvpe** [comment]
Thanks a lot, it's ok now 😓

**Comment by RNabel** [comment]
That's good to hear :) Closing this issue!
