### ISSUE TITLE
How to upload PDF to Google Drive?

### ISSUE THREAD

**Issue by zeluspudding** [googledrive/PyDrive#110]
I've gotten as far as having to set the mime type to `application/pdf`

I short example in the docs would be super appreciated. A short example that loaded a non `.txt` file would be super appreciated.. That way it would illustrate how to load the file into memory, attach is as a payload then send it to google drive.

**Comment by RNabel** [comment]
@zeluspudding Thanks for posting the question here.

Google Drive automatically sets the mimetype (essentially guessing it from the extension). Check out the docs [here](https://pythonhosted.org/PyDrive/filemanagement.html#upload-and-update-file-content) which shows how to upload a png. Let me know if you get it to work that way.

**Comment by zeluspudding** [comment]
Excellent - I figured it out! Very slick!

Although, I can't seem to figure out a way to specify the folder I want to upload a file to. So far I've tried:

```
file = drive.CreateFile({'title': 'my.pdf',
                         'parents': ['0B8K1Jq0f9odZNWlKUXMwZVJuZms']}) # folder ID
# Read file and set it as a content of this instance.
file_path = r'C:\path_to\my.pdf'
file.SetContentFile(file_path)
file.Upload() # Upload the file.
```

with no luck. How can I do that?

**Comment by zeluspudding** [comment]
Huuzaah! I figured it out... was missing the id dict. For those coming here with the same question, here's how to upload a file into a specific Google drive folder:

```
file = drive.CreateFile({'title': 'my.pdf',
                         'parents': [{"id": '0B8K1Jq0f9odZNWlKUXMwZVJuZms'}]})
# Read file and set it as a content of this instance.
file_path = r'C:\path_to\my.pdf'
file.SetContentFile(file_path)
file.Upload() # Upload the file.
print('title: %s, mimeType: %s' % (file['title'], file['mimeType']))
```

**Comment by zeluspudding** [comment]
@RNabel, is it possible to set permissions on a file so that a file can be uploaded and permissioned correctly in one request? This doesn't seem to set permissions.

```
file = drive.CreateFile({'title': 'my.pdf',
                         'parents': [{'id': '0B8K1Jq0f9odZNWlKUXMwZVJuZms'}],
                         'userPermission': {'value': 'anyone',
                                            'type': 'anyone',
                                            'role': 'reader'}})
...
...
file.Upload()
```
I'm hoping this is possible since I have 9.5k pdfs I need to upload. Thanks in advance!

**Comment by RNabel** [comment]
@zeluspudding awesome to hear that you figured out most of the problems you encountered! Also, awesome to post all of this - I'm sure this will turn out to be useful in the future.

From the [API docs](https://developers.google.com/drive/v2/reference/files/insert) I can't see a way to add the permissions with the insert operation. 
To make this as fast as possible you can use a multithreaded setup so the permission changes' round trip time (e.g. a few hundred milliseconds) won't hold up the uploads. I'd suggest having a thread handling the permissions and two or three handling the uploads (maybe using [queues](https://docs.python.org/2/library/queue.html) to assign jobs to each). You are allowed to make 10 API requests per second; pretty sure you won't hit that limit.

If you end up writing a multithreaded uploader, feel free to share it here! 

Let me know if you run into any other hurdles! (closing this for now)

**Comment by zeluspudding** [comment]
Solid. Will update with any code of value. Thanks again!

**Comment by zeluspudding** [comment]
# Multi-threaded/bulk upload to Google Drive
```
# Upload all pdfs and make them publicly viewable

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import json
import os
from multiprocessing.dummy import Pool as ThreadPool
import numpy as np

#%% 
def pp_json(json_thing, sort=True, indents=4):
    # Pretty print json or nested dictionaries
    if type(json_thing) is str:
        print(json.dumps(json.loads(json_thing), sort_keys=sort, indent=indents))
    else:
        print(json.dumps(json_thing, sort_keys=sort, indent=indents))
    return None

def upload_files(file_list):
    # Upload files and set permissions
    for file_name in file_list:
        file = drive.CreateFile({'title': file_name,
                                 'parents': [{'id': gdrive_folder_id}]})
        # Read file and set it as a content of this instance.
        file_path = os.path.join(ocred_pdfs, file_name)
        file.SetContentFile(file_path)
        file.Upload() # Upload the file.
        file.InsertPermission({'type': 'anyone',
                                'value': 'anyone',
                                'role': 'reader'})
    return None

#%% Setup configs and Authenticate
base_path = r'C:\path_to\project'
ocred_pdfs = os.path.join(base_path, r'data\my_files')
gauth = GoogleAuth()
gauth.LocalWebserverAuth() #Creates local webserver and auto handles authentication.
drive = GoogleDrive(gauth)

#%% Determine which files have already been uploaded
gdrive_folder_id = '0B8K1Jq0f9odZeUs4QkQxdnJmSms' #Set your own folder id
file_list = drive.ListFile({'q': "'%s' in parents" % gdrive_folder_id}).GetList()
uploaded_file_names = [file['title'] for file in file_list]

#%% Upload remaining files
pdf_names = list(set(os.listdir(ocred_pdfs)) - set(uploaded_file_names))
worker_file_chunks = np.array_split(pdf_names, len(pdf_names)/10)
workers = 5

#%% Distribute scraping tasks to workers
pool = ThreadPool(workers) # Make the Pool of workers
pool.map(upload_files, worker_file_chunks)
pool.close() #close the pool and wait for the work to finish
pool.join()
print('*** Program END ***')

#%% Inspect uploaded files
file_list = drive.ListFile({'q': "'%s' in parents" % gdrive_folder_id}).GetList()
file_names = []
for file in file_list:
    file_names.append(file['title'])
    
pp_json(file_list[0])
```
Cheers!

**Comment by RNabel** [comment]
@zeluspudding that's a really nice solution - thank you for posting it here!
