### ISSUE TITLE
Supports Python3?

### ISSUE THREAD

**Issue by SalvaJ** [googledrive/PyDrive#15]
This module supports Python3 version?

**Comment by Kedrigern** [comment]
Bump?

**Comment by lared** [comment]
Bump

**Comment by RNabel** [comment]
The version on GitHub is now compatible with Python 3. The [README](https://github.com/googledrive/PyDrive#how-to-install) describes how to install the GitHub version.

**Comment by lared** [comment]
Lovely. Thank you.
