### ISSUE TITLE
Documentation for Upload() unclear

### ISSUE THREAD

**Issue by agryson** [googledrive/PyDrive#18]
I can successfully and repeatedly authenticate and upoad small files, but as soon as I start uploading larger files (~200Mb), PyDrive returns `MemoryError`. 
I would like to pass a `resumable=true` parameter but it's unclear how to do so and the PyDrive documentation provides no examples that I've found.
I've tried `backup.Upload({"resumable": "true"})` and variants but get errors such as `TypeError: Got an unexpected keyword argument "resumable"`
(running Upload() with no parameters works fine for files of a few kb)
A simple example of passing _any_ parameter to `Upload()` would be very helpful.

**Comment by RNabel** [comment]
This was due to #27 and has been resolved with the newest version.
