### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by sander76** [googledrive/PyDrive#21]
Somehow I don't want to give permission each time I start my code. Is there a way to do this?

**Comment by RNabel** [comment]
Thanks @hadim will add this information to FAQ section.

**Comment by bpoti001** [comment]
Hi @hadim I have created the setting.yaml file, but not sure where to save it so that Pydrive can use it.

**Comment by RNabel** [comment]
Hi @bpoti001, the file should be in the same location as the script (or the context from where you are executing the script from). If you have a look at [auth.py](https://github.com/googledrive/PyDrive/blob/master/pydrive/auth.py#L156), the `GoogleAuth()` call just uses a default value of `settings.yaml` for the `settings_file` parameter. If you want to use a different file name or location just pass the path to `GoogleAuth()`:

```python
settings_path = 'settings/settings.yaml'  # i.e. if settings.yaml is located in the subfolder `settings`
gauth = GoogleAuth(settings_file=settings_path)
```

**Comment by sakeerpkn** [comment]
Hi 

But in my credentials.json refresh_token is alkways null.  Why it so?
For that I am getting the below error now. 

`raise RefreshError('No refresh_token found.'
pydrive.auth.RefreshError: No refresh_token found.Please set access_type of OAuth to offline.`
