### ISSUE TITLE
thread safety

### ISSUE THREAD

**Issue by joe42** [googledrive/PyDrive#25]
Hi,

Is PyDrive thread-safe (or at least the Upload method)? Or is there a way to create an independent copy of the GoogleDrive instance? I tried to deepcopy the drive and also to create a new drive with the same GoogleAuth object. But I get a BadStatusLine: '' Error when trying to create and upload a new file with it.

Thx,
joe

**Comment by RNabel** [comment]
@joe42 Thank you for sharing this code! The library will be made thread-safe in the next days.
