### ISSUE TITLE
Any plans to port this to Python 3?

### ISSUE THREAD

**Issue by hgrecco** [googledrive/PyDrive#26]

**Comment by sbma44** [comment]
bumping this -- anyone home?

**Comment by pferate** [comment]
I've updated this to work with Python 3 in my fork (PR #45).  I've also updated google-api-python-client and oauth2client to both work with Python 3, those got merged into the master branches already.

**Comment by MrSchism** [comment]
To be clear, it remains 2x compatible as well, right?

**Comment by pferate** [comment]
@MrSchism: yes, all of the tests pass in 2.6, 2.7, 3.3, and 3.4.  I'll get it tested for 3.5 once I get it installed on my system.

**Comment by juanpablovega** [comment]
Any news on Python 3.5?

I get this error:

from pydrive.auth import GoogleAuth

Traceback (most recent call last):
...
    from pydrive.auth import GoogleAuth
  File "C:\Python35\lib\site-packages\pydrive\auth.py", line 160
    except socket.error, e:
                                  ^
SyntaxError: invalid syntax
...

**Comment by pferate** [comment]
It looks like the version on PyPI hasn't been updated in a while. The latest master commit should work with 3.5.

@aliafshar, would it be possible to update the release on PyPI?  Is there anything that could be done by the community to help make that easier for you?  Or do you want a Googler to do the release prep?

**Comment by RNabel** [comment]
@pferate I am cleaning up the repo and will upload the new version to PyPI in the next week.
