### ISSUE TITLE
Is this the only way to create a new blank spreadsheet?

### ISSUE THREAD

**Issue by andybak** [googledrive/PyDrive#31]
Took me a fair while to figure it out. It seems a touch unintuitive:

    file = drive.CreateFile()
    file = drive.CreateFile({'title': sheet_name})
    file['mimeType'] = 'application/vnd.google-apps.spreadsheet'
    file.Upload()

**Comment by michaeleekk** [comment]
I think you can write something just like:

```
file = drive.CreateFile({'title': sheet_name, 'mimeType: 'application/vnd.google-apps.spreadsheet'})
file.Upload()
```

**Comment by RNabel** [comment]
Agreed, not easy to find a way to do @michaeleekk's approach will work, and I'll add this to the documentation.
