### ISSUE TITLE
file-delete function added on PyDrive

### ISSUE THREAD

**Issue by ytakefuji** [googledrive/PyDrive#33]
Hi,
I have added a new function: DeleteFile() in files.py
The following five lines should be added in the end of files.py
The indentation should be cared.

*def DeleteFile(self,file_id):
****try:
******self.auth.service.files().delete(fileId=file_id).execute()
**except errors.HttpError, error:
*****print 'An error occurred: %s' % error

To generate files.pyc, you need to compile files.py.
help.py can be used to compile the target files.py.
$ cat help.py
import py_compile
py_compile.compile("files.py")
$ chmod 755 files.py
$ python help.py
You should have files.pyc

See my example using the delete function on Google Drive:
https://github.com/ytakefuji/PyDrive/blob/master/oauth2_delete.py

**Comment by RNabel** [comment]
#60 which also implements this functionality has been merged.
