### ISSUE TITLE
Upload to directory

### ISSUE THREAD

**Issue by wernight** [googledrive/PyDrive#34]
Is there a supported way to upload to a given directory instead of the root?

**Comment by wernight** [comment]
Ok I found the answer:

 1. https://drive.google.com then locate a folder, right click to get share link, and note the ID in the URL
 2. Like described on https://developers.google.com/drive/web/folder#inserting_a_file_in_a_folder:

    "parents": [{
      "kind": "drive#childList",
      "id": "HERE_COMES_THE_LONG_LONG_ID"
    }]

**Comment by RNabel** [comment]
An example has been added to the examples folder.

**Comment by Deepakchawla** [comment]
thks it's working
