### ISSUE TITLE
Installing pydrive through Pip causes an error

### ISSUE THREAD

**Issue by TheBrenny** [googledrive/PyDrive#40]
When importing PyDrive, after installing with the command `sudo -H pip install -t "/usr/local/lib/python2.7/dist-packages" PyDrive`, the import fails when attempting to import a PyDrive dependency, `httplib2`.

This issue has probably risen due to not porting PyDrive to Python3...

Wouldn't it just be viable to use `lib2to3` to convert it all to Py3?

**Comment by RNabel** [comment]
A python 3 port will be merged soon, see #47.
