### ISSUE TITLE
Unable to access "permissions" dictionary key for file resource.

### ISSUE THREAD

**Issue by deltaray** [googledrive/PyDrive#41]
I'm not having trouble authenticating with google drive.

When I try to access the dictionary key for a google drive file called 'permissions' I receive an error:

```
Authentication successful.
title: [document name snipped], id: [id of file snipped]
permissions:


Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    permissions = file1['permissions']
  File "/home/myusername/.local/lib/python2.7/site-packages/pydrive/files.py", line 113, in __getitem__
    raise KeyError(e)
KeyError: KeyError('permissions',)
```

I'm using this code based on the sample documentation code:

```
from pprint import pprint
from pydrive.auth import GoogleAuth

gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Creates local webserver and auto handles authentication

from pydrive.drive import GoogleDrive
drive = GoogleDrive(gauth)

file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()
for file1 in file_list:
    print 'title: %s, id: %s\npermissions:\n\n' % (file1['title'], file1['id'])
    permissions = file1['permissions']
    pprint(permissions)
    print '\n\n'
```

I'm able to access any of the other google drive API keys in the documentation including ownerName and userPermission, but not permissions. Any idea why?

**Comment by pferate** [comment]
It looks like it is using [v1 of the API](https://developers.google.com/drive/v1/reference/files).  The key you are looking for is `userPermission`.

**Comment by pferate** [comment]
It looks like it should be using v2 of the drive API, which should include the `permissions` key.  It may be an upstream issue, I'll try to look into this.

**Comment by RNabel** [comment]
@pferate is right, it is using v2, and the key you are looking for is `userPermissions`.

**Comment by RNabel** [comment]
@pferate is right, it is using API v2, and the key is `userPermission`. So in your code: `file1['userPermission']`
