### ISSUE TITLE
Seems no maintenance? out of date.

### ISSUE THREAD

**Issue by jaseywang** [googledrive/PyDrive#43]
Most of time it raises:  `FileNotDownloadableError: No downloadLink/exportLinks for mimetype found in metadata` due to the `<class 'pydrive.files.GoogleDriveFile'>` , the format of `GoogleDriveFile` class seems changed a lot, currently no work, at least can't download file to local.
Below is the trace:
<pre>
---------------------------------------------------------------------------
FileNotDownloadableError                  Traceback (most recent call last)
<ipython-input-36-999895ff33ec> in <module>()
      1 for file1 in file_list:
----> 2     file1.GetContentString()
      3

/Library/Python/2.7/site-packages/pydrive/files.pyc in GetContentString(self)
    154     """
    155     if self.content is None or type(self.content) is not io.BytesIO:
--> 156       self.FetchContent()
    157     return self.content.getvalue().decode('utf-8')
    158

/Library/Python/2.7/site-packages/pydrive/files.pyc in _decorated(self, *args, **kwargs)
     34     if not self.uploaded:
     35       self.FetchMetadata()
---> 36     return decoratee(self, *args, **kwargs)
     37   return _decorated
     38

/Library/Python/2.7/site-packages/pydrive/files.pyc in FetchContent(self, mimetype)
    208
    209     raise FileNotDownloadableError(
--> 210         'No downloadLink/exportLinks for mimetype found in metadata')
    211
    212   def Upload(self, param=None):

FileNotDownloadableError: No downloadLink/exportLinks for mimetype found in metadata
</pre>

**Comment by RNabel** [comment]
@jaseywang I am currently bringing everything up to date. A number of updates have been made --> please use the new version from GitHub, and post here if you are still encountering this issue.
