### ISSUE TITLE
Issues while installing it with pip

### ISSUE THREAD

**Issue by rajeshyogeshwar** [googledrive/PyDrive#51]
When I tried installing pydrive via pip, it installed python 2.x version, I was infact hoping for python 3. Further when I tried pip install git+https://github.com/googledrive/PyDrive.git, it still resulted in python 2 version. I want the python 3 version in my application. Let me know if I am doing something wrong here.

Ubuntu OS 14.04
Virtual Environment created with python 3.4

**Comment by lawrencebenson** [comment]
it seems pydrive was not yet updated in pypi, as the updated date is 2014-04-04. however I cloned it and put it in my virtualenvs site-packages and it get the correct python3 compatible version. how do you make out that it is the "python 2 version" that you are running?

**Comment by rajeshyogeshwar** [comment]
I checked out the file with.py the print statements were in python 2 syntax

-----Original Message-----

**Comment by lawrencebenson** [comment]
maybe just mixed something up when cloning. the only file I see containing `print` statements is the `auth.py` and in my case, it's all `print()`. make sure you delete the old pydrive folder, just to be safe

**Comment by rajeshyogeshwar** [comment]
I will try it again and let you know if the issue persists

-----Original Message-----

**Comment by lawrencebenson** [comment]
nonetheless, @aliafshar @jgwak is it possible to get the current master in PyPI?

**Comment by RNabel** [comment]
The new version is going to be updated on PyPI soon.
