### ISSUE TITLE
Exception raised on shutdown

### ISSUE THREAD

**Issue by lawrencebenson** [googledrive/PyDrive#52]
When I close the python program, the following message pops up multiple times:
   
    Exception ignored in: <bound method ApiAttribute.__del__ of 
        <pydrive.apiattr.ApiAttribute object at 0x7f819e8dabe0>>
    TypeError: __del__() missing 1 required positional argument: 'obj'

I am running this code off the master, not PyPI, in Python 3.4. 

Any ideas what is causing this error?

**Comment by RNabel** [comment]
PR merged, so closing this issue.
