### ISSUE TITLE
Push to PyPi

### ISSUE THREAD

**Issue by nhumrich** [googledrive/PyDrive#59]
I see that this code is now compatible with python3. But it hasn't been pushed to pypi since. 
Could the code be pushed so those of us who are up to date can use this?

**Comment by RNabel** [comment]
This will be done in the coming weeks after catching up on the back-log of PRs and issues.

**Comment by nhumrich** [comment]
its worth noting that I already pushed this to pypi https://pypi.python.org/pypi/PyDrive3
If you would like me to delete this once its uploaded to pypi and supports python3, let me know

**Comment by RNabel** [comment]
Great, thank you for letting me know! I'll give you a heads up once the new version is ready and pushed. 
Since you are an active user of the library, what are your thoughts on transitioning to PEP8?

**Comment by nhumrich** [comment]
pep8 is good. Its a python standard. Do it.

**Comment by hosford42** [comment]
Any word on this? I'm having the same issue:

```
Python 3.4.5 |Anaconda 2.1.0 (64-bit)| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydrive.auth import GoogleAuth
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\pydrive\auth.py", line 160
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
```

**Comment by RNabel** [comment]
Yep, this is hopefully going to happen very soon (exact time frame unknown since this library is nobody's main assignment atm). Meanwhile, you can resolve this issue by following the installation instructions [here](https://github.com/googledrive/PyDrive#how-to-install) to install the GitHub version with pip.

**Comment by moigagoo** [comment]
So, it's been three weeks. Any update?

Installation instructions are of no use if you want to make PyDrive a requirement in setup.py since it doesn't have syntax for git-based installation.

**Comment by RNabel** [comment]
I am chasing it up - I'll keep you posted. 
Meanwhile, there is a temporary workaround on [StackOverflow](http://stackoverflow.com/a/29682273/3918512). I hope this helps!

**Comment by nhumrich** [comment]
another workaround is you can just `pip install PyDrive3`

**Comment by moigagoo** [comment]
@RNabel Thanks for the update!

@nhumrich Using that for now.

**Comment by RNabel** [comment]
Just got access to the PyPI repo - version 1.2.1 is now on PyPI! Wohoo :) 

@nhumrich thank you for providing a temporary solution! Could you update the `README` of `PyDrive3` to indicate that the original repo is now up-to-date again?

**Comment by nhumrich** [comment]
sure thing
