### ISSUE TITLE
No tests to verify large downloads work.

### ISSUE THREAD

**Issue by RNabel** [googledrive/PyDrive#62]
All files are downloaded into io.BytesIO objects which store all contents in RAM and could result in files larger than the available space resulting in a crash.

**Comment by Fjodor42** [comment]
IIRC correctly, I made a, now accepted (thank you) PR for large file *upload*.

I also commented on an issue regarding downloading, giving a code sample, but I don't believe I actually got around to actually make a PR, but if you could do so yourself, that would be great, as I don't have much time on my hands...

**Comment by RNabel** [comment]
@Fjodor42, thank you for the heads up - I just had a look at your comment. The library will need changes to the internal download mechanism for downloading, e.g. allowing the user to provide a file handle / file name when downloading the content.
