### ISSUE TITLE
File permissions not changing

### ISSUE THREAD

**Issue by gpires** [googledrive/PyDrive#63]
When I try to change permissions of same file to allow sharing by updating its metadata. The file is uploaded

    drive = GoogleDrive(gauth)
    file1 = drive.CreateFile({'title': 'hello.txt', 'shareable':True,  'userPermission': [{'kind':'drive#permission', 'type': 'anyone', 'value': 'anyone','role': 'reader'}]})
    file1.SetContentFile('hello.txt')
    file1.Upload()
    print(file1['userPermission'])
However, when I print the userPermission, it doesn't seem to have set the permissions as I have intended.

I get:

    {u'kind': u'drive#permission', u'etag': u'"TEeH8_qJkyJwjXXXXXXXXXXX/JoK_XXXXXXXXXXXXXXXXX"', u'role': u'owner', u'type': u'user', u'id': u'me', u'selfLink': u'https://www.googleapis.com/drive/v2/files/0B7vnOfySXXXXXXXXXXXXXX/permissions/me'}

**Comment by RNabel** [comment]
Alright, I found the problem. The permissions are set correctly, but they do not show up as a special `permissions

**Comment by gpires** [comment]
My idea was to create a file that can be shared with anyone I took a [print](http://i.imgur.com/PmFY1Zy.jpg) after I uploaded using the code above.

**Comment by RNabel** [comment]
Thanks for the update, and yep that's what I thought you are trying to do - a pretty essential functionality of the library.
It should be easy to fix, but I won't have time to look into this until tomorrow. 

If you need this to work soon, my current assumption is that the values you are passing are rejected for some reason. When setting the permission through the UI, it sets a couple of other fields, and provides a different `value` field. 
1) Create a file, 2) Set the Share settings such that anyone with the link can view it, extract the file ID from the link generated, and plug the file id into `permissions.list` [API tester](https://developers.google.com/drive/v2/reference/permissions/list#try-it).

The output I get is:
```
   "kind": "drive#permission",
   "etag": "\"TEeH8_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxzI3AgxZRxabSQ\"",
   "id": "anyoneWithLink",
   "selfLink": "https://www.googleapis.com/drive/v2/files/0B-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/permissions/anyoneWithLink",
   "role": "reader",
   "type": "anyone",
   "withLink": true
```

**Comment by RNabel** [comment]
@gpires new feature for permission handling was just added. Have a look at the updated [documentation](https://googledrive.github.io/PyDrive/docs/_build/html/filemanagement.html#insert-permissions).
