### ISSUE TITLE
Exception: AttributeError: 'GoogleDriveFileList' object has no attribute 'auth_method'

### ISSUE THREAD

**Issue by srodriguex** [googledrive/PyDrive#65]
I'm in PythonAnywhere.com cloud service running a Python3.5 environment. 
I successfully cloned and installed this repo in this env.
Following the example, I successfully authorized, as none exception was thrown at my face, using a local credential.json file. 
Unfortunately, the listing files example raised me the exception `"AttributeError: 'GoogleDriveFileList' object has no attribute 'auth_method'"`. Googling about it I couldn't find any useful information.
Bellow is the full stack:

```
AttributeErrorTraceback (most recent call last)
<ipython-input-15-f4a2609ca408> in <module>()
      1 # Auto-iterate through all files that matches this query
----> 2 file_list = drive.ListFile({'q': "'root' in parents"}).GetList()
      3 for file1 in file_list:
      4   print('title: %s, id: %s' % (file1['title'], file1['id']))

/home/srodriguex/MYENV/lib/python3.5/site-packages/PyDrive-1.1.2-py3.5.egg/pydrive/apiattr.py in GetList(self)
    160       self['maxResults'] = 1000
    161       result = []
--> 162       for x in self:
    163         result.extend(x)
    164       del self['maxResults']

/home/srodriguex/MYENV/lib/python3.5/site-packages/PyDrive-1.1.2-py3.5.egg/pydrive/apiattr.py in __next__(self)
    144     if 'pageToken' in self and self['pageToken'] is None:
    145       raise StopIteration
--> 146     result = self._GetList()
    147     self['pageToken'] = self.metadata.get('nextPageToken')
    148     return result

/home/srodriguex/MYENV/lib/python3.5/site-packages/PyDrive-1.1.2-py3.5.egg/pydrive/auth.py in _decorated(self, *args, **kwargs)
     53     # Re-create access token if it expired.
     54     if self.auth.access_token_expired:
---> 55       if self.auth_method == 'service':
     56         self.auth.ServiceAuth()
     57       else:

AttributeError: 'GoogleDriveFileList' object has no attribute 'auth_method'
```

**Comment by RNabel** [comment]
Hi @srodriguex, short answer:
auth.py:55 should be `if self.auth_method and self.auth_method == 'service':` If you have access to the file you can just edit this line.

Long answer: this should have been adressed by one of last week's commits, but must have slipped through the net. I'll include this fix in the next patch which is going to be pushed either today or tomorrow.

**Comment by RNabel** [comment]
@srodriguex the bug has been fixed!

**Comment by srodriguex** [comment]
I appreciate the fast answer. Unfortunately it got a new error:

```
/home/srodriguex/MYENV/lib/python3.5/site-packages/PyDrive-1.2.0-py3.5.egg/pydrive/auth.py in _decorated(self, *args, **kwargs)
     53     # Re-create access token if it expired.
     54     if self.auth.access_token_expired:
---> 55       if getattr(self, 'auth_method', default=False) == 'service':
     56         self.auth.ServiceAuth()
     57       else:

TypeError: getattr() takes no keyword arguments
```

**Comment by RNabel** [comment]
@srodriguex Try # 2: could you verify whether the current version resolves the bug?

**Comment by srodriguex** [comment]
It seems it's all right now. I should have noticed the error in the `getattr` function. Thank you for this awesome library. It saves us a lot of time.
