### ISSUE TITLE
Can't download files.

### ISSUE THREAD

**Issue by jeremy-seipelt** [googledrive/PyDrive#66]
Hi I get the following issue:

```
Authentication successful.
(u'Hello.txt', u'application/vnd.google-apps.document')
Traceback (most recent call last):
  File "quickstart.py", line 18, in <module>
    file2.GetContentFile(file1['title'],file1["mimeType"])
  File "/Library/Python/2.7/site-packages/pydrive/files.py", line 167, in GetContentFile
    self.FetchContent(mimetype)
  File "/Library/Python/2.7/site-packages/pydrive/files.py", line 36, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pydrive/files.py", line 210, in FetchContent
    'No downloadLink/exportLinks for mimetype found in metadata')
pydrive.files.FileNotDownloadableError: No downloadLink/exportLinks for mimetype found in metadata
```

Here is how my code looks like now:
```
   
from pydrive.auth import GoogleAuth

gauth = GoogleAuth()
gauth.LocalWebserverAuth() # Creates local webserver and auto handles authentication.

from pydrive.drive import GoogleDrive

# Create GoogleDrive instance with authenticated GoogleAuth instance.
drive = GoogleDrive(gauth)
# Auto-iterate through all files that matches this query
file_list = drive.ListFile({'q': "'root' in parents and trashed=false"}).GetList()
for file1 in file_list:
  file2 = drive.CreateFile({'id': file1['id']})
  print(file1["title"], file1["mimeType"])
  file2.GetContentFile(file1['title']) #download the file

```
I am new to python so I am assuming that i did something wrong even if I use examples from the doc.

**Comment by RNabel** [comment]
The mime type of the file indicates that it is a Google Docs file. These files require you to specify the file type you want to download it as. For example: Download a Google Drive Document as Microsoft Word file. 
In order to download all files from GDrive (which seems to be what you are doing) I would suggest you define a dict which maps the Google Drive file type to its desired download mime type.

In your code prior to the loop, define a dict similar to this:
```
mimetypes = {
    # Drive Document files as MS Word files.
    'application/vnd.google-apps.document': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',

    # Drive Sheets files as MS Excel files.
    'application/vnd.google-apps.spreadsheet': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

    # etc.
}
```
You can find a list of the mime types Google Drive uses [here](https://developers.google.com/drive/v2/web/mime-types), and a list of mime types you can convert these to [here](http://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc/4212908#4212908).

You can then adapt the loop to handle these mimetypes:

```
for file1 in file_list:
    download_mimetype = ''
    if file1['mimeType'] in mimetypes:
        download_mimetype = mimetypes[file1['mimeType']]

    file1.GetContentFile(file1['title'], mimetype=download_mimetype)
```
**Note**: You don't need to create a new file object to download the file. Further, the maximum file size you can download with PyDrive is currently limited by the size of your memory.

Have a look at [this PyDrive issue](https://github.com/googledrive/PyDrive/issues/64) for an example of requesting a file with a specific mimetype, and if `mimetype=mimetype` seems confusing have a look at the [Python docs on Keyword Arguments](https://docs.python.org/2/tutorial/controlflow.html#keyword-arguments).

Hope this helps!

**Comment by jeremy-seipelt** [comment]
It worked. But you have to indent the last line to prevent non listed mimetypes.

Folder in my root director have mimetype= none  which throws the error i had.

**Comment by RNabel** [comment]
Good to hear! Could you paste the error / exception you encountered when running the exact code?

The default value of the parameter mimetype in `GetContentFile` is `None`, so it would be surprising if a non-handled mimetype, in this case a non-GDrive file, which results in `download_mimetype` to be `None`, would cause the code above to break.

**Comment by jeremy-seipelt** [comment]
With your snippet:
```
for file1 in file_list:
    download_mimetype = None
    if file1['mimeType'] in mimetypes:
        download_mimetype = mimetypes[file1['mimeType']]

    file1.GetContentFile(file1['title'], mimetype=download_mimetype)

```
I get the following: 

```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    file1.GetContentFile(file1['title'], mimetype=download_mimetype)
  File "/Library/Python/2.7/site-packages/pydrive/files.py", line 167, in GetContentFile
    self.FetchContent(mimetype)
  File "/Library/Python/2.7/site-packages/pydrive/files.py", line 36, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/pydrive/files.py", line 210, in FetchContent
    'No downloadLink/exportLinks for mimetype found in metadata')
pydrive.files.FileNotDownloadableError: No downloadLink/exportLinks for mimetype found in metadata
```

If i change it to :
for file1 in file_list:
    download_mimetype = None
    if file1['mimeType'] in mimetypes:
        download_mimetype = mimetypes[file1['mimeType']]
        file1.GetContentFile(file1['title'], mimetype=download_mimetype)

it works and throws no error. I think it breaks with the folder mimetype because he downloads some files but not all with your code.

**Comment by RNabel** [comment]
You have to add a default behavior for Google Drive-files which you do not want to download. My suggestion would be to just skip all files with a Google Drive mimetype which you are not explicitely handling (such as folders). 

Thus, the code would look like this:
```
for file1 in file_list:
    download_mimetype = None
    current_mimetype = file1['mimeType']

    #  Check if file's mime type is Google Drive-file type.
    if 'application/vnd.google-apps' in current_mimetype:
        
        if file1['mimeType'] in mimetypes:  # Check if mime type is handled.
            download_mimetype = mimetypes[file1['mimeType']]
        else:  # Skip file if mime type is not handled.
            continue

    file1.GetContentFile(file1['title'], mimetype=download_mimetype)
```

Note, however, that Google Drive has no naming restrictions, so downloading all files into one folder can easily result in name collisions. Such collisions would lead to files with the same name being overwritten.

**Comment by jeremy-seipelt** [comment]
Yeah already changed the code to my preferences.
 ```
def checkFile(arg):
    if arg['mimeType'] in mimetypes:
        print('The file ' + str(arg['title']) + ' has a mimetype of ' + arg['mimeType'] + ' and will be    downloaded')
        downloadFile(arg)
        return
    if arg['mimeType'] in folder:
        print('The file ' + str(arg['title']) + ' has a mimetype of ' + arg['mimeType'] + ' and will be entered')
        enterFolder(arg['id'])
    return

def enterFolder(query):
    file_list = drive.ListFile({'q': '\'' + query + '\' in parents and trashed=false'}).GetList()
    for file1 in file_list:
        checkFile(file1)
    return

def downloadFile(arg):
   download_mimetype = None
   download_mimetype = mimetypes[arg['mimeType']]
   arg.GetContentFile(arg['title'], mimetype=download_mimetype)
   print(arg['title'] + 'got downloaded')
   return

```

and I added another dictionary

```
folder = {
    # Comparing for folder.
    'application/vnd.google-apps.folder': 'true'
    # etc.
}
```
