### ISSUE TITLE
use https for manual pip install from github

### ISSUE THREAD

**Issue by crmackay** [googledrive/PyDrive#71]
corporate firewalls are annoying, but nevertheless exist...and they often don't have unusual ports open (like 9418, which is what the git protocol uses).

github allows https, and https is always available, so I would just change the line in the [github docs](https://googledrive.github.io/PyDrive/docs/_build/html/index.html) from:

```
$ pip install -e git+git@github.com:googledrive/PyDrive.git#egg=PyDrive
```
to 
```
$ pip install -e git+https://github.com/googledrive/PyDrive.git#egg=PyDrive
```

**Comment by RNabel** [comment]
Thank you for pointing this out! Docs are now updated :+1:
