### ISSUE TITLE
Example of creating and using folders

### ISSUE THREAD

**Issue by asamite** [googledrive/PyDrive#72]
I have been trying to cobble together some code that will walk me through creating new folders and then uploading files into them.  I have looked around the interwebz but am new to Python.  Just some examples that show creating a new folder, getting the ID of the folder and then uploading files to this same folder.  Thanks.

**Comment by asamite** [comment]
I figured out the folder creation portion:

#Create folder
folder_metadata = {'title' : 'MyFolder', 'mimeType' : 'application/vnd.google-apps.folder'}
folder = drive.CreateFile(folder_metadata)
folder.Upload()

#Get folder info and print to screen
foldertitle = folder['title']
folderid = folder['id']
print('title: %s, id: %s' % (foldertitle, folderid))

Now I am trying to work through the adding files to a specific folder.  I have the ID from the folder I just created but I haven't gotten the right combination when creating the file using the parents property.

**Comment by asamite** [comment]
Using the last comment as the example for creating a folder, you would then follow on with this to upload a file to that folder:

#Upload file to folder
file = drive.CreateFile({"parents": [{"kind": "drive#fileLink", "id": folderid}]})
file.SetContentFile('testpic.jpg')
file.Upload()

**Comment by RNabel** [comment]
Hey, sorry for the delay, and thank you for providing the examples here! 

I would like to add your code to a new examples section of this repo. @asamite, could you fill out Google's CLA so that I can use the code you provided in this answer? You can find information about it [here](https://cla.developers.google.com/about) and fill it out [here](https://cla.developers.google.com/clas). 

Let me know if you have any questions :)

**Comment by asamite** [comment]
CLA filled out and submitted.  Feel free to use the code I submitted here.  If I have a chance, I will try and put the other code I worked through here as well.  I get that not every permutation of example is possible so we all have to contribute if we can when we run across a new situation.

**Comment by RNabel** [comment]
Awesome, thank you! Feel free to create a pull request to the [development branch](https://github.com/googledrive/PyDrive/tree/development), which already has the `examples` folder.

The more examples the better!

**Comment by proguru2018** [comment]
A question: how do you add permission for an email-id to be able to edit a file? Thanks

**Comment by pmalbu** [comment]
> A question: how do you add permission for an email-id to be able to edit a file? Thanks

This might help you out: https://stackoverflow.com/questions/42685942/google-drive-api-permissions-how-to-disable-findable-by-anyone-on-internet/42697514
