### ISSUE TITLE
Unicode error on Python 3.5 when downloading content

### ISSUE THREAD

**Issue by srodriguex** [googledrive/PyDrive#74]
Don't know if it's really an issue as this library is not yet for Python 3. 

I installed this library directly from the github repository as mentioned in the documentation.

I'm using it to download text files generated by a Brazilian enterprise from Google Drive. It's highly probable the content contains accented characters like ã, é, ç...

When I try to download the content I got the following error:

    ---------------------------------------------------------------------------
    UnicodeDecodeError                        Traceback (most recent call last) 
    <ipython-input-8-717b0bfb8edd> in <module>()
    ----> 1 content.GetContentString()
    /home/srodriguex/.local/lib/python3.5/site-packages/pydrive/files.py in GetContentString(selfmimetype)
    171     if self.content is None or type(self.content) is not io.BytesIO:
    172       self.FetchContent(mimetype)
    --> 173     return self.content.getvalue().decode('utf-8')
    174 
    175 
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 33: invalid continuation byte

The workaround I'm using is to remove the `.decode('utf-8')` in the line 173 above. 

Below there's an example of the content:

    b'"Data","Dependencia Origem","Hist\xf3rico","Data do Balancete","N\xfamero do documento","Valor",\r\n"12/31/2009","","Saldo Anterior","","0","6148.91",\r\n"01/04/2010","","Compra com Cart\xe3o","01/24/0010","79294","-6.78",\r\n"01/04/2010","","Compra com Cart\xe3o","01/24/0010","175284","-4.75",\r\n"01/04/2010","4059-2","Saque no TAA","01/24/001

**Comment by RNabel** [comment]
I have a fix for this more or less ready, and will bundle it with a number of doc updates once they are ready. Fix should be out in the next 2-3 days.

Meanwhile, you can try the following approach. My assumption is that the file which is resulting in this error was uploaded as a file with `SetContentFile()` and `Upload()` and not `SetContentString()` and `Upload()`. If this is the case then the uploaded file is not using the `utf-8` encoding. 

So, you can bake your own `GetContentString()` with a different encoding as follows:

```python
# Insert your encoding here, I would suggest trying ISO-8859-1
your_encoding = 'ISO-8859-1'
f = drive.CreateFile({'id': '<your file id here>'})
f.FetchContent()
content_string = f.content.getvalue().decode(encoding=your_encoding)
```

`ISO-8859-1` (also known as `latin-1`) is a pretty common encoding and covers most of the latin languages, so probably a good start. [Wiki page](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) for reference.

Let me know if you get this to work!

**Comment by srodriguex** [comment]
I worked fine! Thanks!
