### ISSUE TITLE
Allow downloading a spreadsheet in CSV format

### ISSUE THREAD

**Issue by gonvaled** [googledrive/PyDrive#8]
As explained here: http://stackoverflow.com/q/11619805/647991

There is no downloadUrl in the metadata. Instead there is a exportLinks link, for pdf, xlsx and ods. One of those exportLink must be reworked to:
- specify csv as download format: ?exportFormat=csv
- specify the sheet to download (this must be a user-supplied parameter): &gid=0

**Comment by Rosuav** [comment]
I have a spreadsheet that I want to be able to access programmatically. It has multiple worksheets, but the only one my program needs is the first. Hacking in a new URL seems to work:

```
if u'text/csv' not in file.metadata['exportLinks']:
	# Current versions of PyDrive don't provide CSV download links, but it seems quite functional
	file.metadata['exportLinks'][u'text/csv'] = file.metadata['exportLinks'][u'application/pdf'][:-3]+u"csv"
```

**Comment by Rosuav** [comment]
Similarly, it would be nice if GetContentString() could grow a metadata= parameter, to match the GetContentFile(). Want me to put together a PR?
