### ISSUE TITLE
Saving files with the same name creates duplicates

### ISSUE THREAD

**Issue by gcmartinelli** [googledrive/PyDrive#82]
I found no indication on  the docs about how to rewrite a file when uploading it. Is there a way to do it?

**Comment by RNabel** [comment]
Yep, there is a way to do it. To update a remote file, you need to create with `drive.CreateFile({'id': '<your file id>'})` and then perform the action you would like to perform, in your case `SetContentFile()` and `Upload()`.

If you need to get the ID of the file programmatically, you can either list all files or [list files in a specific folder](https://github.com/googledrive/PyDrive/issues/37) and search for the file by name in the list (how to [upload a file to a folder](https://github.com/googledrive/PyDrive/blob/master/examples/using_folders.py) may also come in handy).

A better way to do this, however, would be to use query parameters as described [here](https://developers.google.com/drive/v2/web/search-parameters) when running the `ListFiles()` command, i.e.:
```python
file_list = drive.ListFile({'q': "<your query here>"}).GetList()
```

**Comment by gcmartinelli** [comment]
@RNabel thank you. That worked perfectly
