### ISSUE TITLE
Browser being opened every time script is ran

### ISSUE THREAD

**Issue by WillBishop** [googledrive/PyDrive#94]
```
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive

gauth = GoogleAuth()
gauth.LocalWebserverAuth()

drive = GoogleDrive(gauth)
file1 = drive.CreateFile({'title': 'Helo.txt'})
file1.SetContentString('Hello')
file1.Upload() 
```

That should be simple, but everytime I run it, it opens the browser for authentication

**Comment by RNabel** [comment]
This is intended behaviour. Please check this [StackOverflow post](https://stackoverflow.com/questions/24419188/automating-pydrive-verification-process), which describes how to store a credentials file.
